### ISSUE TITLE
[FEAT] Entity 설계

### ISSUE THREAD

**Issue by Hong0329** [Team-Growthook/Growthook-Server#3]
## 🚀 About Issue 🚀

- Entity 설계를 합니다.

## ✅ Todo 

- [x] 멤버 Entity 구현
- [x] 동굴 Entity 구현
- [x] 씨앗 Entity 구현
- [x] 리뷰 Entity 구현
- [x] 액션 플랜 Entity 구현
