### ISSUE TITLE
[SETTING] 프로젝트 Swagger 3.0 세팅

### ISSUE THREAD

**Issue by Hong0329** [Team-Growthook/Growthook-Server#5]
## 🚀 About Issue 🚀

프로젝트 Swagger 3.0 세팅합니다.

## ✅ Todo 

- [x] dependency 추가
```javascript
// build.gradle 파일
 
dependencies {
    implementation 'org.springdoc:springdoc-openapi-ui:1.6.9'
}
```
- [x] yml 설정 추가
- [x] SwaggerConfig 설정 등록
- [x] HealthCheckAPI를 통해 http://localhost:8080/swagger-ui.html 에서 적용 확인하기
